class MyExceptions:
    def __init__(self):
        pass